### ISSUE TITLE
confidence score

### ISSUE THREAD

**Issue by xiexuliunian** [HiBugs/CenterNet#2]
Thanks for your work!!!
I use this repo to detec my own plate dataset,when I finally get my train model ,this result is just ok ,but the confidence score is usually between from 0.4-0.8,for dectec task this score isn't too low?when I use retinanet for detection task ,the score is usually over 0.95,so can you gave me some advices on how to make the confidence score higher?

**Comment by HiBugs** [comment]
It doesn't matter any way. If you like, you can just multiply the score by two and make them between [0-1].

**Comment by xiexuliunian** [comment]
OK ,Thanks!!!
