### ISSUE TITLE
人脸关键点检测优化有什么策略？

### ISSUE THREAD

**Issue by zhangcj13** [HiBugs/CenterNet#3]
自行训练的数据发现人脸倾斜时，关键点预测不准，在训练上有什么优化策略么？

**Comment by HiBugs** [comment]
你的意思是在自己收集的数据集上训练吗？可能数据不够丰富，可以考虑使用数据增强，增加倾斜人脸的数据等等。如果在公开数据集上训练，应该是没啥大问题的。如果还有问题，可以改一下人脸框的loss和关键点的loss权重之比。

**Comment by zhangcj13** [comment]
@HiBugs  多谢，正在尝试做这些修改后训练
